name = "web-pixel"
type = "web_pixel_extension"


runtime_context = "strict"

[settings]
type = "object"

[settings.fields.company_id]
name = "company_id"
description = "company_id"
type = "single_line_text_field"
validations =  [
  { name = "min", value = "1" }
]
